name: snapspace
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

  # Firebase Core Packages
  firebase_core: ^3.6.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.5.0
  image_picker: ^1.0.7
  firebase_storage: ^12.3.0
  http: ^1.5.0
  url_launcher: ^6.1.10

  # Utils
  random_string: ^2.3.1
  fluttertoast: ^9.0.0
  intl: ^0.20.0
  flutter_launcher_icons: ^0.14.4
  cloudinary_public: ^0.23.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/default_avatar.jpg
    - assets/images/default_booth.jpg
    - assets/data/indonesia_regions.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_medium.ttf
          weight: 500
        - asset: assets/fonts/poppins_semibold.ttf
          weight: 600
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_snapspace.png"
  # Optional: adaptive icon untuk Android
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo_snapspace.png"
